# -*- coding: utf-8 -*-
"""Task_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wYll8DhIt2pzSG_otXwHzGVwb2QB351R
"""

import time

# Generate the number (n) using the provided algorithm
current_time = int(time.time())
generated_number = (current_time % 100) + 50

if generated_number % 2 == 0:
    generated_number += 10

generated_number

from google.colab import drive
drive.mount('/content/drive')

from PIL import Image

# Load the provided image
image_path = '/content/drive/MyDrive/chapter1.jpg'
image = Image.open(image_path)

# Prepare to modify the image
pixels = image.load()
width, height = image.size

# Modify each pixel by adding the generated number to each RGB component
for x in range(width):
    for y in range(height):
        r, g, b = pixels[x, y]
        new_r = min(r + generated_number, 255)  # Ensure the value doesn't exceed 255
        new_g = min(g + generated_number, 255)
        new_b = min(b + generated_number, 255)
        pixels[x, y] = (new_r, new_g, new_b)

# Save the modified image
output_image_path = '/content/drive/MyDrive/Colab Notebooks/chapter1out.png'
image.save(output_image_path)

# Calculate the sum of all red (R) pixel values in the new image
total_red_value = sum(pixels[x, y][0] for x in range(width) for y in range(height))

output_image_path, total_red_value